### ISSUE TITLE
Can't run simple trace command

### ISSUE THREAD

**Issue by peekxc** [ameli/imate#3]
On a fresh pip install with imate, I'm unable to run any methods involving the SLQ method: 

```python
from imate import toeplitz, trace, schatten
A = toeplitz(2, 1, size=100, gram=True)
trace(A, gram=False, p=2.5, method='slq')
# Segmentation fault: 11
```
Putting that script in its own python file and running valgrind yields: 

```bash 
PYTHONMALLOC=malloc valgrind --tool=memcheck --leak-check=full python examples/valgrind_trace.py 
# valgrind: mmap-FIXED(0x0, 602112) failed in UME (load_segment1) with error 12 (Cannot allocate memory).
```

I'll try a source build this afternoon

> Python version: 3.9.12
> Compiled with: Clang 12.0.0
> System: Darwin
> Node Name: MacBook-Pro-8.local
> Release: 19.6.0
> Version: Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64
> Machine: x86_64
> Processor: i386

**Comment by ameli** [comment]
Thank you for bringing this issue to our attention. I've made attempts to reproduce it on various machines and Python versions, but so far, I haven't been able to encounter the problem.

Could you please update the package to the most recent version, 0.20.0, and retest to see if the issue still persists? If it does, it would be immensely helpful if you could provide a more detailed backtrace of the segfault.

Furthermore, it would be useful to determine whether the issue arises exclusively with the ``pip`` installation or if it also occurs when using ``conda`` to install the package.

**Comment by ameli** [comment]
I've managed to replicate the segfault issue you reported. It appears that this problem specifically affects macOS users and if MKL is present through other packages in your Python environment.

This issue is associated with the challenge of handling multiple copies of OpenMP runtime libraries on macOS, and it isn't specific to the imate package itself. To address the segfault problem as a workaround, firstly, if the environment variable ``KMP_DUPLICATE_LIB_OK`` is set to ``True``, unset this variable with

    unset KMP_DUPLICATE_LIB_OK

Next, disable (or remove) MKL:

    conda install nomkl
    conda remove mkl mkl-service

If you come across this issue in different scenarios or find that the above workaround doesn't resolve the problem on your system, please let me know, otherwise, feel free to close the issue.

**Comment by peekxc** [comment]
Ahh, I can confirm the SLQ method now works! Thanks again!
